version: "3.9"
services:
  scraper:
    build: .
    image: afreeca-scraper:latest
    volumes:
      - "./token:/afreeca-scraper/token"
      - "./secrets:/afreeca-scraper/secrets"
      - "./videos:/afreeca-scraper/videos"
      - "./logs:/afreeca-scraper/logs"
    shm_size: '2gb'
    depends_on:
      - "chrome"
    environment:
      - PYTHONUNBUFFERED=1 # print stdout logs immediately when `docker logs -f {containerId}`
  
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
