version: "3.9"
services:
  shinee-scraper:
#    build: .
    image: mojo1821/shinee-scraper:latest
    volumes:
      - "./token:/afreeca-scraper/token"
      - "./secrets:/afreeca-scraper/secrets"
      - "./videos:/afreeca-scraper/videos"
      - "./logs:/afreeca-scraper/logs"
      - "./configs:/afreeca-scraper/configs"
    shm_size: '2gb'
    depends_on:
      - chrome
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1 # print stdout logs immediately when `docker logs -f {containerId}`
      - ENV=${ENV} # set this to an appropriate value (possible values: prod, dev)
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  
  chrome:
    image: mojo1821/standalone-chrome:latest # copied version of selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
